amadeus_demo_api/amadeus_demo_api/settings.py
amadeus_demo_api/amadeus_demo_api/urls.py
amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/login/admin.py
amadeus_demo_api/login/apps.py
amadeus_demo_api/login/models.py
amadeus_demo_api/login/templates/login/tmp.html
amadeus_demo_api/login/tests.py
amadeus_demo_api/login/urls.py
amadeus_demo_api/login/views.py
amadeus_demo_api/static/js/apiClient.js
amadeus_demo_api/static/js/getCookie.js
amadeus_demo_api/users/services.py
amadeus_demo_api/users/templates/users/login.html
amadeus_demo_api/users/urls.py
amadeus_demo_api/users/urls_front.py
amadeus_demo_api/users/views.py
run.sh

- [] 가이드라인에 맞춘 커밋 메시지 작성
- [] 수정된 빌드 환경 커밋 완료
* 내용 추가
|기능|스크린샷|
|로그인 페이지|![image](https://github.com/user-attachments/assets/77ca08e8-0c2d-4315-92cb-fc8c4de9434f)|
|로그인 성공|![image](https://github.com/user-attachments/assets/c14b0c58-5d20-4bc5-bde5-3c210ebfddf1)|
|채팅|![image](https://github.com/user-attachments/assets/7933a4a7-1e97-427c-88ab-a4557274c164)|
- [ "x"] 기능 추가
- [ "x"] 빌드, 패키지 관련 수정
<기능 추가>
- 로그인 페이지 구현 완료
- 로그인 후 유저 인증하고, 인가해주도록 axios handler 작성함
채팅에서 검색 api로 요청 보내면 400에러 뜸.
이건 post body 양식을 안 맞춰서 그런거고, 일단 인가는 된 것임.
<빌드, 패키지 관련 수정>
axios를 로컬에 설치해야 함. 로컬에서 개발하는 분들 master 브랜치 pull 하시고 npm으로 axios 설치하셔야 돼요!
html파일에서는 웹에 설치된 axios를. (얘는 브라우저에서 열리니까)
apiClient.js에서는 로컬에 설치된 axios를 사용함.
둘 중 한 방법만 사용하려면 …

로그인, auth 기능 구현 완료

---

.gitignore
ai/main.py
requirements.txt

[feat] ai서버 생성

---

Dockerfile
ai/Dockerfile
ai/requirements.txt
docker-compose.yml
requirements.txt

Django 포트번호 : 8081
Fastapi 포트번호 : 8080

[feat] docker 추가

---

amadeus_demo_api/chatbot/views.py

* 내용 추가
django 서버랑 연결되는지 확인하는 api입니다. 확인용
|기능|스크린샷|
|----|-----|
|||
> 현재 수정 중인 부분(필수), 머지 후 다른 멤버들이 주의해서 봐야 할 수정사항 등을 설명해주세요.
api/chat/ask/ 
post 
{
"chat_history": [
"질문1",
"답변1",
"질문2",
"답변2",
"질문3"
]
}
형태로 전달.
해당하는 답변은 ai server response와 동일. 이후로 해당 type가지고 어떤 booking인지 체크 후 해당 분기로 이동(booking api에 명시 되어있는형태)

feat:ai server mapping

---

amadeus_demo_api/amadeus_demo_api/settings.py
amadeus_demo_api/chatbot/views.py

* 내용 추가
ai server 연결 test code 
|기능|스크린샷|
|----|-----|
|||

test:ai server연결

---

amadeus_demo_api/chat/templates/chat/chat.html

* 서버와 통신 후 response에서 data를 처리하는 과정에서, 비동기를 고려하지 않아 수정
|기능|스크린샷|
|----|-----|
|||

fix: 비동기 문제 해결

---

ai/ai.py
ai/main.py
ai/requirements.txt

정확도 향상을 위해 Langchain 코드를 Langgraph 코드로 변경.
하나의 프롬프트가 작업하던 것을 총 5개의 프롬프트로 분리함.
|기능|스크린샷|
|----|-----|
|diagram|![image](https://github.com/user-attachments/assets/61015282-0239-420c-8791-fd96eb8ae2c9)|
ai.py를 추가해서 Langgraph코드를 넣었고, main.py에는 ai.py를 호출하는 식으로 만들었습니다.
정확도 향상을 위해 만든거라 기능은 동일하니 팀원분들 고려하실 사항은 없습니다^^

Langchain -> Langgraph로 변경

---

amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/chat/templates/chat/chat_session.html

* 네비게이션에서 채팅 세션 클릭하여 이동하는 기능 추가
* 백엔드 /chat/ask에서 채팅 외에 세션 id도 같이 저장하게 수정해주세요. -> 백엔드 /chat/history에서 채팅 히스토리 db에서 조회할 때 세션 id 고려해서 조회하도록 수정해야 할 것 같아요.
* https://www.notion.so/API-1fc829b9e082804ea1b7c13e4d0ee10a 참고해주세요.
|기능|스크린샷|
|----|-----|
|채팅 세션 별 히스토리 조회|![image](https://github.com/user-attachments/assets/2209f58a-58c3-44ac-b4c1-3222efe5641d)|
로컬에서 유저 채팅 렌더링 시간이 너무 오래 걸림.

feat: 내비게이션에서 채팅방 클릭하여 이동

---

amadeus_demo_api/booking/dispatch.py
amadeus_demo_api/chatbot/admin.py

* 내용 추가
mapping - booking이랑 price 연동 . (price가 필요한데, 이전에는 각각 구분해서 진행한다면, 이번에는 묶어서 한번에 예약까지 가능하도록.)
*****아직 test중임 ******** 
|기능|스크린샷|
|----|-----|
|||
추가: admin page에 model 어떤식으로  저장되는지 확인용으로 몇 개 넣어놓음.

feat:mapping-booking

---

ai/ai.py
ai/aiv1.py
ai/search.json
ai/test.py

* Langchain버전, Langgraph버전을 비교하는 test 코드 추가
* test를 위한 Search Question data 추가
* "adults": False를 반환해야하는 상황에 0을 반환하는 경우가 있는데 False로 반환하도록 수정
* 마찬가지로 "number"에 대해서도 수정
|기능|스크린샷|
|----|-----|
|||

adults value 오류 수정

---

amadeus_demo_api/booking/amadeus.py
amadeus_demo_api/booking/dispatch.py
amadeus_demo_api/chatbot/views.py

* 내용 추가
|기능|스크린샷|
|----|-----|
|||
cancel, 예약 관련 명령어 수정(기능 추가 및 오류 수정), 아직 완전하지 x

feat:mapping-취소,예약(수정)

---

amadeus_demo_api/booking/views.py

* 내용 추가
버그 수정: 예약할 때 잘못된 함수 호출 수정
|기능|스크린샷|
|----|-----|
|||

fix:예약생성 관련 오류 수정

---

amadeus_demo_api/booking/dispatch.py

* 내용 추가
bug fix: cancel관련 버그 수정
debug 추가: 예약 후 조회 관련 디버그용 코드 추가
|기능|스크린샷|
|----|-----|
|||

debug:디버그용 코드 추가

---

amadeus_demo_api/booking/views.py

* 내용 추가
fix: 디코딩 처리(예약 후 조회)
|기능|스크린샷|
|----|-----|
|||

fix:예약 후 조회시 %같은디코딩 처리

---

amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/chat/templates/chat/chat_session.html
amadeus_demo_api/chat/templates/handlers.js
amadeus_demo_api/static/chat/js/handlers.js

* 노션의 api 명세서에 작성된 내용 토대로 항공권 예약, 검색 요청에 대한 답변을 처리하여 화면에 렌더링하는 기능을 구현했습니다.
|기능|스크린샷|
|----|-----|
|||
- [] 버그 수정
* 로컬에서 제대로 테스트를 못해서 서버에서 작동 안 될 수도 있습니다.

/chat/ask의 response 화면에 렌더링

---

amadeus_demo_api/booking/dispatch.py
amadeus_demo_api/booking/views.py

* 내용 추가
|기능|스크린샷|
|----|-----|
|||
api 명세 수정 (노션 참고)

fix: 명세 관련 버그 및 수정

---

amadeus_demo_api/amadeus_demo_api/urls.py
amadeus_demo_api/static/login/js/login.js
amadeus_demo_api/users/templates/users/login.html
amadeus_demo_api/users/templates/users/mypage.html
amadeus_demo_api/users/views.py

* 내용 추가
|기능|스크린샷|
|----|-----|
|||

fix: 마이페이지 에러 수정

---

amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/chatbot/models.py
amadeus_demo_api/chatbot/urls.py
amadeus_demo_api/chatbot/views.py
amadeus_demo_api/static/chat/js/handlers.js
amadeus_demo_api/static/users/js/mypage4.js
amadeus_demo_api/users/templates/users/mypage.html

* 세션별 대화 기록 저장
models.py에서 db 구조 변경: sessionId, title 이 저장된 테이블 추가, chat history 테이블도 sessionId 열이 포함되도록 수정
/api/chat/sessions 로 지금까지 생성한 채팅방 내역 받아오는 기능 추가
/api/chat/history 에서 세션아이디까지 고려해서 저장하고, 찾아올 때도 세션 아이디로 조회해서 찾아오도록 수정
* 
|기능|스크린샷|
|----|-----|
|세션별 대화|![image](https://github.com/user-attachments/assets/06bb9901-b9ec-48c3-a5a8-b7b3e8a7a170)|
llm api 응답 이상합니다. 직접 랭체인으로 확인하는 것도 좋은데, 서버로 접속하셔서 직접 테스트 해보면서 이상한 경우 발견하고 수정 좀 해주세요.
그리고 chatbot 앱 내부에 models.py 랑 views.py에 채팅기록테이블, 관련 함수들 수정되었으니 참고해주세요.

세션별 대화 기록 저장

---

amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/static/chat/js/handlers.js

* 6.11일에 수정된 API response에 맞추어 답변을 화면에 렌더링 할 수 있는 핸들러를 추가했습니다. 모든 타입의 답변에 대한 핸들러를 추가했습니다.
|기능|스크린샷|
|----|-----|
|||
- [] 버그 수정

feat: 모든 응답에 대한 handler 추가

---

amadeus_demo_api/booking/views.py
amadeus_demo_api/chatbot/models.py
amadeus_demo_api/chatbot/views.py

* 내용 추가
chathistory에 answer필드는 기본: ai 서버에서 오는 답변 저장
게다가 추가적인 ai_answer필드를 넣어서 (오타, 아마데우스 answer로 넣어야 하는데 ai로 해버림) 아마데우스 서버에서 전달받은 api 가공해서 프론트에 전달하는 데이터를 저장하도록 함. 
|기능|스크린샷|
|----|-----|
|||
노션 수정예정

feat:chathistory model update & log update

---

amadeus_demo_api/booking/dispatch.py
amadeus_demo_api/booking/utils.py
amadeus_demo_api/chatbot/admin.py

* 내용 추가
이전꺼 실수로 저장 안하고 커밋해서 다시 커밋
|기능|스크린샷|
|----|-----|
|||

feat: chathistory model 수정(아까 저장 안하고 커밋해버려서 다시)

---

amadeus_demo_api/chatbot/views.py

* 내용 추가
버그수정
|기능|스크린샷|
|----|-----|
|||

feat: chathistory관련 버그 수정

---

amadeus_demo_api/chatbot/views.py

* 내용 추가
채팅 기록 api, 기록 가지고 ai서버 호출 할 때 
기존에는 ai서버에서 응답받은것 그대로 json에 넣어서 전달했다면
지금은 아마데우스 서버 api 응답받아서 작성한 데이터가 존재한다면(에러 없이 호출 완료) 그 데이터가 넘어갑니다. 
즉, ChatHistoryView 호출 시 기존은 
"인천에서 출발하고 런던공항으로 가는 비행기를 찾아줘",
{'type': 'search', 'success': True, 'originLocationCode': 'ICN', 'destinationLocationCode': 'LHR', 'departureDate': '2025-07-01', 'adults': 1}
형태였다면
지금은 성공했으면 
"인천에서 출발하고 런던공항으로 가는 비행기를 찾아줘",
{"type": "search", "status": "success", "message": "Flight search successful.", "search_id": 2, "flightOffers": [{"id": "1", "departure_airport": "ICN", "arrival_airport": "LHR", "departure_time": "2025-07-01T18:05:00", "arrival_time": "2025-07-02T16:55:00", "price": "303.40 USD", "airline": "EY", "number_of_stops": 1}, {"id": "2", "departure_airport": "ICN", …

feat: 채팅기록수정

---

amadeus_demo_api/chat/templates/chat/chat.html
amadeus_demo_api/static/chat/js/handlers.js

* 네비게이션 아래 버튼들 적절한 이름으로 수정, 연결 링크 주소 수정
* 챗봇 답변 줄바꿈 조정
* 
|기능|스크린샷|
|----|-----|
|||

채팅 화면 관련 에러들 수정
